spring:
  profiles:
    active: dev
  application:
    name: zuul-server

server:
  port: 9990

zuul:
  sensitive-headers: Access-Control-Allow-Origin,Cookie,Set-Cookie # fix error: multiple Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,Cookie,Set-Cookie # 如果客户端在发请求是带了Cookie，那么Cookie依然会传递给下游服务。但是如果下游服务再转发就会被过滤。

  routes:
    user-service: /user/**
    uploadexcel-service: /uploadexcel/**
    companyipo-service: /companyipo/**
    search-service: /search/**
    exchange-service: /exchange/**

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
    
#"hystrix.command." + commandKey + ".execution.isolation.thread.timeoutInMilliseconds" #单独服务的超时设置

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
  
---
spring:
  profiles: dev
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    
logging:
  config: classpath:logback-spring.xml # dev log config
 
---
spring:
  profiles: prod
  
eureka:
  client:
    service-url:
      defaultZone: http://106.54.194.33:8761/eureka/   # server eureka
    healthcheck:
      enabled: true
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    
logging:
  config: classpath:logback-prod.xml # pro log config

